# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2466c660e99410c25198ab04290d2fa7a676dede474d1490375ffb730a42f900a074692dff3126894b7394def3aecdae8cd9cd44ee7d14247d3d8458b1ba2b72

test:
  secret_key_base: 47c9b5a3360a6c607ac36fff386b986acd7c68b9f9503acabacabfb38d0b70da33c3f26f1aedcd659c010af13f53e0ebc986b53a34fae1f71543851c3c2adbdb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
